---
title: "klava: parameter optimzation with mrgsolve"
output: github_document
---

```{r,echo=FALSE}
knitr::opts_chunk$set(comment='.',fig.path="inst/img/README-")
```

## Installation
```{r,eval=FALSE}
devtools:::install_github("kylebaron/klava")
```

## Example
```{r include=FALSE}
requireNamespace("nlme")
```

```{r , message=FALSE}
library(dplyr)
library(mrgsolve)
library(nloptr)
library(ggplot2)
library(rlang)
library(klava)
```


Load an mrgsolve model
```{r}
mod <- modlib("pk2")
```

# Grab some data
```{r}
data <- readRDS("inst/dat/2cmtA.RDS")

ggplot(data, aes(time,DV)) + geom_point() + theme_bw()
```

The data is more or less in NONMEM-type format
```{r}
data
```


# Define a parameter list
```{r}
theta <- all_log(CL = 0.5, V2 = 50, Q = 1.1, V3 = 30, KA = 1.1, sigma=1.1)
```

This is a self-transforming vector
```{r}
theta
```

```{r}
trans(theta)
```

That also supports fixed values
```{r}
foo <- quick_par(CL = log(1), KA = fixed(1.1), F1 = logit(0.8))

foo

trans(foo)

untrans(trans(foo))
```


# Fit the model

```{r}
fit <- fit_nl(theta, data, mod = mod, pred_name= "CP", cov_step=TRUE,
              pred_initial=TRUE)
```

Result
```{r}
fit$tab
```

# Diagnostics

```{r, warning=FALSE}
plot(fit)
```


```{r,warning = FALSE}
ggplot(fit$data, aes(time,RES)) + geom_point() + 
  geom_hline(yintercept=0) + theme_bw()
```


```{r, warning = FALSE}
ggplot(fit$data, aes(PRED,DV)) + geom_point() + 
  geom_abline(intercept = 0, slope = 1) + theme_bw()
```


## Objective functions

Extended Least Squares - ELS
```{r}
fit <- fit_nl(theta, data, mod, pred_name= "CP", ofv=els)
```

Normal likelihood
```{r}
fit <- fit_nl(theta, data, mod, pred_name= "CP", ofv=ml)
```

Ordinary Least Squares - OLS
```{r}
fit <- fit_nl(theta, data, mod, pred_name= "CP", ofv=ols)
```

Weighted Least Squares - WLS
```{r}
fit <- fit_nl(theta, data, mod, pred_name= "CP", ofv=wls)
```
