#' Simulate internal example data
library(mrgsolve)
library(dplyr)
library(nloptr)
car <- c("amt", "evid", "ii", "addl", "ss", "rate", "cmt")
mod <- modlib("pk2")
des1 <- tgrid(0,36,6)
des2 <- tgrid(0,6,1,add = c(0.25))
des <- c(des1,des2)
e <- ev(amt = 100)
out <- mrgsim_e(mod,e,recsort=2,tgrid=des,carry_out = car,req="")

data <- mutate_sims(out,DV = CP*exp(rnorm(n(),0,sqrt(0.001))),mdv=evid,CP=NULL)
data <- select(data, ID, time, evid, mdv,everything())
data <- filter(data, !(DV==0 & evid==0))
saveRDS(file="inst/data/2cmtA.RDS",data)
